apiVersion: v2
name: capi-node-labeler
version: 1.1.6-dev
appVersion: 1.1.6-dev
description: "CAPI node labeler"
home: "https://github.com/giantswarm/capi-node-labeler-app"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: "phoenix"
  io.giantswarm.application.team: "phoenix"
